import demo from "./assets/png/demo.jpg";
const product = [
  {
    id: 1,
    image: demo,
    category: "Stationary",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "Book",
    price: 10,
    quantity: 1,
  },
  {
    id: 2,
    image: demo,
    category: "Gadget",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "Watch",
    price: 40,
    quantity: 1,
  },
  {
    id: 3,
    image: demo,
    category: "Gadget",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "Headphones",
    price: 19,
    quantity: 1,
  },
  {
    id: 4,
    image: demo,
    category: "Laptops",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "Asus Rog Flow X13",
    price: 599,
    quantity: 1,
  },
  {
    id: 5,
    image: demo,
    category: "Phones",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "Samsung Galaxy",
    price: 240,
    quantity: 1,
  },
  {
    id: 6,
    image: demo,
    category: "Gadget",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "Powerbank",
    price: 29,
    quantity: 1,
  },
  {
    id: 7,
    image: demo,
    category: "Gadget",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "Charger",
    price: 31,
    quantity: 1,
  },
  {
    id: 8,
    image: demo,
    category: "Laptops",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "MacBook M2",
    price: 229,
    quantity: 1,
  },
  {
    id: 9,
    image: demo,
    category: "Laptops",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "Dell Inspiron",
    price: 349,
    quantity: 1,
  },
  {
    id: 10,
    image: demo,
    category: "Laptops",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "HP Pavillion",
    price: 489,
    quantity: 1,
  },
  {
    id: 11,
    image: demo,
    category: "Phones",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "Vivo Y16",
    price: 249,
    quantity: 1,
  },
  {
    id: 12,
    image: demo,
    category: "Phones",
    disc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    tittle: "Oppo A77S",
    price: 279,
    quantity: 1,
  },
];
export default product;
